plugins:
  - jekyll-feed
  - jekyll-sitemap
include:
  - _pages
  - _projets
theme: jekyll-theme-cayman
repository: paysagealternatif/website
header_pages:
  - about
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /blog/:path/
  projets:
    output: true 
    permalink: /:path/  
title: Paysages Alternatifs
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
email: paysage.alternatif@gmail.com
description: Entreprise paysagiste basée à Chatte, dans l'isère. 

  
